### PR TITLE
* Add support for organizing Redirects into categories

### PR DESCRIPTION
**Pull request by raamdev**
- Create custom hierarchical taxonomy 'redirect_category' to allow categorizing redirects. This is extremely helpful when sites have a large number of redirects.

### CODE REVIEW

**Comment by jaswrks** [comment]
Nice :-) I will review shortly.

**Comment by jaswrks** [comment]
I'm merging this in now, and I will test it myself soon before I commit to Wordpress.org. Thanks for adding translation support there too. I need to update the other parts of this plugin to add translation support in other areas also.

**Comment by raamdev** [comment]
I was just thinking about how I named the new taxonomy `redirect_category` and I was thinking that it might be possible for that to cause a conflict, as I can see someone else creating a `redirect_category` taxonomy for something else.

That made me think about the `redirect` Custom Post Type name that this plugin is using. That name seems extremely generic and could potentially cause a conflict where another plugin creates the same Custom Post Type.

In any case, doesn't it make more sense to name those `ws_redirect` and `ws_redirect_category`? Neither of those names will show up anywhere on the front-end of the plugin anyway.

**Comment by jaswrks** [comment]
> That made me think about the redirect Custom Post Type name that this plugin is using. That name seems extremely generic and could potentially cause a conflict where another plugin creates the same Custom Post Type.

Yea, I agree it is generic. Although I think perhaps we deserve that name. This is the WP Redirect plugin after all :-) I would agree to changing it though. However, I believe changing it now would break existing installations of this plugin; because existing redirects are stored in the `wp_posts` table with column name `post_type` = `redirect`.

**Comment by raamdev** [comment]
>  However, I believe changing it now would break existing installations of this plugin; because existing redirects are stored in the wp_posts table with column name post_type = redirect.

Good point. I guess we should just leave things as-is then. For future reference, I think it's always good to err on the side of assuming that somebody else's plugin will cause a conflit which would make our plugin look bad, regardless of how much we deserve the name. ;)

**Comment by jaswrks** [comment]
Agreed :-)

**Pull request merged**
